services:
  # 1. Microservicio de Usuarios
  ms-users:
    image: nginx:alpine
    command: >
      sh -c "echo '{\"service\": \"users\", \"status\": \"online\"}' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  # 2. Microservicio de Productos
  ms-products:
    image: nginx:alpine
    command: >
      sh -c "echo '{\"service\": \"products\", \"count\": 150}' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  # 3. Frontend (Tu carpeta local /html)
  frontend:
    image: nginx:alpine
    volumes:
      - ./html/front:/usr/share/nginx/html:ro

  # 4. El NGINX Principal (Proxy Inverso / Gateway)
  nginx-gateway:
    image: nginx:latest
    container_name: nginx-gateway-container
    ports:
      - "8181:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf:/etc/nginx/conf.d:ro
    depends_on:
      - ms-users
      - ms-products
      - frontend
