services:
  app1:
    build: ./backend/products
    container_name: spring_app_1
    expose:
      - "8080"
  app2:
    build: ./backend/products
    container_name: spring_app_2
    expose:
      - "8080"
  app3:
    build: ./backend/products
    container_name: spring_app_3
    expose:
      - "8080"

  nginx-lb:
    image: nginx:alpine
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - nginx-cache:/var/cache/nginx
    depends_on:
      - app1
      - app2
      - app3

volumes:
  nginx-cache:
