services:
  mi-app-backend:
    image: nginx:alpine
    container_name: backend-app
    volumes:
      - ./html:/usr/share/nginx/html:ro # Corregido: volumes y /usr/
    # No exponemos puertos para mantenerlo privado tras el proxy

  servidor-practica:
    image: nginx:latest
    container_name: my-nginx-container
    ports:
      - "8181:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      # Estructura recomendada:
      - ./conf:/etc/nginx/conf.d:ro # Configuraciones de sitios específicos
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Configuración global
      - ./logs:/var/log/nginx
    depends_on:
      - mi-app-backend
