user nginx;
worker_processes auto;

# Bloque de eventos (Obligatorio)
events {
    worker_connections 1024;
}

# Bloque HTTP (Aquí vive toda la configuración web)
http {
    # Directiva include: carga tipos de archivos (CSS, JS, etc.)
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    # Definimos un formato llamado "especial"
    log_format especial '[$time_local] '
                        'Cliente:$remote_addr -> Proxy:$host '
                        'Status:$status '
                        'Peticion:"$request" '
                        'Upstream_Addr:$upstream_addr '   # <--- Muestra qué microservicio respondió
                        'Tiempo_Respuesta:$upstream_response_time ' # <--- Cuánto tardó el microservicio
                        'User_Agent:"$http_user_agent"';
    # Aplicamos el log de acceso usando ese formato
    access_log /var/log/nginx/balanceo-acccess.log especial;
    error_log /var/log/nginx/balanceo-error.log info;

    # Aquí le decimos que cargue nuestros archivos de sitios
    include /etc/nginx/conf.d/dominios.conf;
    include /etc/nginx/conf.d/cache.conf;
    include /etc/nginx/conf.d/balanceo.conf;

    # --- UPSTREAM (Backend) ---
    upstream cluster_spring_backend {
        ip_hash;
        server app1:8080 max_fails=3 fail_timeout=30s;
        server app2:8080 max_fails=3 fail_timeout=30s;
        server app3:8080 max_fails=4 fail_timeout=30s;
    }

    # --- CACHE ---
    proxy_cache_path /var/cache/nginx/productos levels=1:2 keys_zone=cache_productos:100m max_size=500m inactive=60m use_temp_path=off;

    # --- RATE LIMITING ---
    limit_req_zone $binary_remote_addr zone=zona_api:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=zona_buscar:10m rate=5r/s;
    limit_req_zone $binary_remote_addr zone=zona_cache:10m rate=20r/s;

    # --- DEBUG & TIMEOUTS ---
    # Si el microservicio tarda, que NGINX no mate la conexión tan rápido
    proxy_connect_timeout 90;
    proxy_send_timeout 90;
    proxy_read_timeout 90;
    # Aumenta el tamaño de los buffers para evitar errores 502/504 con cabeceras grandes
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;

    # --- SEGURIDAD BASICA ---
    server_tokens off; # Oculta la versión de NGINX en los errores (Seguridad)

    # --- PERFORMANCE ---
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
}
