user nginx;
worker_processes auto;

# Bloque de eventos (Obligatorio)
events {
    worker_connections 1024;
}

# Bloque HTTP (Aquí vive toda la configuración web)
http {
    # Directiva include: carga tipos de archivos (CSS, JS, etc.)
    include /etc/nginx/mime.types;

    # Definimos un formato llamado "especial"
    log_format especial '[$time_local] IP:$remote_addr Solicitud:"$request" Status:$status';
    # Aplicamos el log de acceso usando ese formato
    access_log /var/log/nginx/acccess.log especial;
    error_log /var/log/nginx/error.log warn;

    # Aquí le decimos que cargue nuestros archivos de sitios
    include /etc/nginx/conf.d/reverse-proxy-ad.conf;
}
