upstream cluster_spring_backend {
    # Algoritmo Round Robin por defecto
    server app1:8080 max_fails=3 fail_timeout=30s;
    server app2:8080 max_fails=3 fail_timeout=30s;
    server app3:8080 max_fails=4 fail_timeout=30s;
}

server {
    listen 80;
    location /api/ {
        proxy_pass http://cluster_spring_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        # Añadimos una cabecera para ver qué IP interna nos respondió
        add_header X-Backend-Server $upstream_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
