server {
    listen 80; # Nginx escucha internamente en el 80
    server_name misitio.local;  # Nombre del servidor

    location / {
        root /usr/share/nginx/html; # Carpeta donde están los archivos
        index index.html; # Archivo por defecto
    }
}