server {
    listen 80; # Nginx escucha internamente en el 80
    server_name misitio.local;  # Nombre del servidor

    #configuracion de error
    error_page 404 /error404.html;

    location = /error404.html {
        root /usr/share/nginx/html;
        internal; # Esto hace que solo Nginx pueda servir esta página, no el usuario
    }

    # 1. Coincidencia por PREFIJO (Cualquier cosa que empiece con /documentos)
    location /documents {
        return 200 "You are watching the documents folder";
    }

    # 2. Coincidencia EXACTA (Solo si la URL es exactamente /contacto)
    location = /contact {
        return 200 "You are watching the contact page";
    }
    
    # 3. EXPRESIÓN REGULAR (Busca archivos que terminen en .jpg, .png, etc.)
    # El ~* significa: insensible a mayúsculas
    location ~* \.(jpg|jpeg|png)$ {
        return 200 "You request an image, but I won't give it to you. Sorry Baby!";
    } 

    # PRIORIDAD 4: Prefijo normal (La más común)
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Redirección Simple (301 - Permanente)
    location /google {
        return 301 https://www.google.com;
    }

    # Rewrite (Cambia la URL internamente sin que el usuario lo note)
    # Si entras a /servicio/limpieza -> Nginx busca /limpieza
    rewrite ^/servicio/(.*)$ /$1 break;
    
    # Habilitar Gzip
    gzip on;
    gzip_types text/plain text/css application/json;

    # Caché del navegador para imágenes
    location ~* \.(ico|css|js|gif|jpe?g|png)$ {
        expires 30d; # El navegador guardará estas fotos por 30 días
        add_header Cache-Control "public, no-transform";
    }
}