server {
    listen 80; # Nginx escucha internamente en el 80
    server_name misitio.local;  # Nombre del servidor

    # 1. Coincidencia por PREFIJO (Cualquier cosa que empiece con /documentos)
    location /documents {
        return 200 "You are watching the documents folder";
    }

    # 2. Coincidencia EXACTA (Solo si la URL es exactamente /contacto)
    location = /contact {
        return 200 "You are watching the contact page";
    }
    
    # 3. EXPRESIÓN REGULAR (Busca archivos que terminen en .jpg, .png, etc.)
    # El ~* significa: insensible a mayúsculas
    location ~* \.(jpg|jpeg|png)$ {
        return 200 "You request an image, but I won't give it to you. Sorry Baby!";
    } 
}