server {
    listen 80;
    server_name gateway.local;
    #configuracion de error
    error_page 404 /error404.html;

    # 1. DNS Resolver (Google) - Obligatorio para nombres de dominio externos
    resolver 8.8.8.8 valid=30s;
    location /api/external/posts {
        # Usamos variables para que NGINX no falle si la API externa no responde al iniciar
        set $posts_api "https://jsonplaceholder.typicode.com/posts";

        proxy_ssl_server_name on; # Necesario para HTTPS
        proxy_pass $posts_api;

        # Forzamos el Host que espera el servidor de destino
        proxy_set_header Host jsonplaceholder.typicode.com;
        add_header X-Proxy-Source "Backend-Posts-External";
    }




    # RUTA 1: Si la URL empieza con /api/users
    location /api/users {
        # Esta cabecera ayuda a depurar: añade un texto a la respuesta
        add_header X-Proxy-Passed "Si, pase por el Proxy de Clein";
        # Reescribimos la ruta si el microservicio espera solo /
        rewrite ^/api/users/(.*) /$1 break;
        # OJO: Si la URL es exactamente /api/products (sin barra al final),
        # a veces el regex anterior no la atrapa. Usamos esta versión más robusta:
        rewrite ^/api/users/?(.*) /$1 break;
        proxy_pass http://ms-users:80;
        proxy_set_header Host $host;
    }

    # RUTA 2: Si la URL empieza con /api/products
    location /api/products {
        # Esta cabecera ayuda a depurar: añade un texto a la respuesta
        add_header X-Proxy-Passed "Si, pase por el Proxy de Clein";
        # Reescribimos la ruta si el microservicio espera solo /
        # Esta línea es el "borrador": quita /api/products y deja solo /
        rewrite ^/api/products/(.*) /$1 break;

        # OJO: Si la URL es exactamente /api/products (sin barra al final),
        # a veces el regex anterior no la atrapa. Usamos esta versión más robusta:
        rewrite ^/api/products/?(.*) /$1 break;
        proxy_pass http://ms-products:80;
        proxy_set_header Host $host;
    }

    # RUTA 3: Todo lo demás va al Frontend
    location / {
        # Esta cabecera ayuda a depurar: añade un texto a la respuesta
        add_header X-Proxy-Passed "Si, pase por el Proxy de Clein";
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
    }
}
