# Definimos el servidor que recibirá las peticiones
    server {
        listen 80;
        server_name reverse-proxy.local;

        location / {
            # Esta cabecera ayuda a depurar: añade un texto a la respuesta
            add_header X-Proxy-Passed "Si, pase por el Proxy de Clein";
            # 2. La directiva estrella: Pasa la petición al contenedor backend
            # Docker resuelve 'mi-app-backend' automáticamente a su IP interna
            proxy_pass http://mi-app-backend:80;

            # 3. Configuraciones de Cabeceras (FUNDAMENTAL)
            # Sin esto, el backend creerá que todas las visitas vienen de NGINX

            # Mantiene el nombre del dominio original (localhost)
            proxy_set_header Host $host;

            # Pasa la IP real del usuario al backend
            proxy_set_header X-Real-IP $remote_addr;

            # Si hay varios proxies, mantiene la cadena de IPs
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Indica si el usuario usó http o https originalmente
            proxy_set_header X-Forwarded-Proto $scheme;

            # 4. Tiempos de espera (Timeouts)
            # Evita que conexiones lentas bloqueen tu servidor
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
}
